import Vapor
import SportsCalModel
import VaporAPNS
import APNSCore
import RediStack

/// In-process last-known-good cache for near-static payloads served straight
/// from Redis. A transient Redis failure (timeout, pool exhaustion, dropped
/// connection) on the `/teams` read was rethrowing as HTTP 500 — Sentry
/// `SPORTS-CAL-38` logged 356 of these across 7 users, and the app reads an
/// empty/failed teams fetch as "no games / unknown team" (see the ★1 review).
/// Teams data changes rarely, so serving the last good payload turns those
/// blips into a slightly-stale success instead of a hard failure.
actor LastKnownGoodCache {
    static let shared = LastKnownGoodCache()
    private var teams: String?
    func storeTeams(_ value: String) { teams = value }
    var teamsValue: String? { teams }
}

/// Resolve which APNS gateway issued the device token in this request. The iOS
/// client signals it via the `X-APNS-Env: sandbox|production` header so the
/// hint stays out of URLs and access logs. Older clients that don't send the
/// header fall back to the server's own environment for back-compat — this
/// matches the prior single-environment behavior on a per-server basis.
func resolveAPNSEnvironment(from req: Request) -> APNSEnvironment {
    if let raw = req.headers.first(name: "X-APNS-Env"),
       let env = APNSEnvironment(rawValue: raw) {
        return env
    }
    return req.application.environment == .development ? .sandbox : .production
}

/// Per-install stable identifier (UUID generated by the app on first launch,
/// persisted in Keychain). All push-to-start state is keyed by this so an APNS
/// token rotation doesn't leave a duplicate registration shadowing the new one.
/// Falls back to the supplied push token (legacy clients pre-install-id header)
/// so any duplicate it causes is at worst self-inflicted from a single device.
func resolveInstallID(from req: Request, fallbackToken: String) -> String {
    if let raw = req.headers.first(name: "X-Install-ID"), !raw.isEmpty {
        return raw
    }
    return "legacy-\(fallbackToken)"
}

func routes(_ app: Application) throws {
    // Register API version middleware globally
    app.middleware.use(APIVersionMiddleware())

    // MARK: - Unauthenticated ping
    // Cheap reachability probe used by the iOS app to auto-pick between local,
    // dev (Tailscale), and prod servers. Must stay outside rate limiting and
    // API-key middleware so HEAD requests from the env picker are free.
    app.get("ping") { _ in "pong" }
    app.on(.HEAD, "ping") { _ in HTTPStatus.ok }

    // MARK: - Development-only routes (log streaming)
    if app.environment == .development {
        // Log Streaming WebSocket
        app.webSocket("ws", "logs") { req, ws async in
            await LogBroadcaster.shared.addSubscriber(ws)

            // `ws.onText`'s setter asserts it runs on the connection's event loop, but this async
            // closure executes in a detached Task off the loop — register on `ws.eventLoop`.
            ws.eventLoop.execute {
            ws.onText { ws, text in
                // Parse filter commands from client
                guard let data = text.data(using: .utf8),
                      let json = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
                      let type = json["type"] as? String, type == "filter" else {
                    return
                }

                var filter = LogFilter()

                if let levelStr = json["level"] as? String,
                   let level = Logger.Level(levelStr) {
                    filter.minLevel = level
                }

                if let labels = json["labels"] as? [String], !labels.isEmpty {
                    filter.labels = Set(labels)
                }

                if let search = json["search"] as? String, !search.isEmpty {
                    filter.searchText = search
                }

                Task {
                    await LogBroadcaster.shared.updateSubscriberFilter(ws, filter: filter)
                }
            }
            }

            // Keep alive until disconnect
            try? await ws.onClose.get()
            await LogBroadcaster.shared.removeSubscriber(ws)
        }
    }

    // MARK: - Admin Routes
    // Gated by ADMIN_API_KEY_HASH in every environment. AdminKeyMiddleware fails
    // closed if the env var is unset, so registering these unconditionally is safe.
    let adminRoutes = app.grouped(AdminKeyMiddleware())
    try adminRoutes.register(collection: AdminController())
    try adminRoutes.register(collection: ParityController())

    // MARK: - Versioned Routes (v2025)
    // Rate limit runs before the API key check so unauthed floods get 429'd
    // after the threshold instead of costing one Redis hit per 403.
    let v2025 = app.grouped(RateLimitMiddleware(limit: 300, windowSeconds: 60, keyPrefix: "rl:v2025"))
        .grouped("v2025")
        .grouped(APIKeyMiddleware())
    registerAPIRoutes(on: v2025, app: app)

    // MARK: - Legacy Routes (unversioned)
    // Keep for backward compatibility with older app versions
    let legacy = app.grouped(RateLimitMiddleware(limit: 300, windowSeconds: 60, keyPrefix: "rl:legacy"))
        .grouped(APIKeyMiddleware())
    registerAPIRoutes(on: legacy, app: app)

    // MARK: - Universal Links (public, unauthenticated)
    // Serves the apple-app-site-association at the well-known path with the
    // correct content type and NO redirect, so iOS validates `applinks:` for
    // shared game + World Cup bracket links. appID = <TeamID>.<BundleID>.
    // NOTE: requires the link host's DNS to point here + the Associated Domains
    // entitlement on the app before universal links resolve to the app.
    app.get(".well-known", "apple-app-site-association") { _ async -> Response in
        let json = """
        {"applinks":{"apps":[],"details":[{"appID":"9GDU5ZNHX7.com.KomodoLLC.SportsCal","paths":["/g/*","/wc/*"]}]}}
        """
        var headers = HTTPHeaders()
        headers.contentType = .json
        return Response(status: .ok, headers: headers, body: .init(string: json))
    }

    // Web fallback for recipients without the app: a tiny page that shows the
    // App Store smart banner and bounces to the listing. When the app IS
    // installed, iOS opens it directly (universal link) and never renders this.
    let appStoreURL = "https://apps.apple.com/app/id1580232928"
    func appStoreFallback(_ title: String) -> Response {
        let html = """
        <!doctype html><html><head><meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="apple-itunes-app" content="app-id=1580232928">
        <title>\(title) · Scoreline</title>
        <meta http-equiv="refresh" content="0; url=\(appStoreURL)">
        </head><body><p>Opening Scoreline… <a href="\(appStoreURL)">Get the app</a>.</p></body></html>
        """
        var headers = HTTPHeaders()
        headers.contentType = .html
        return Response(status: .ok, headers: headers, body: .init(string: html))
    }
    app.get("g", ":id") { _ async -> Response in appStoreFallback("Game") }
    app.get("wc", "bracket") { _ async -> Response in appStoreFallback("World Cup Bracket") }
}

/// Registers all API routes on a given route builder.
/// This allows the same routes to be registered under both versioned and legacy paths.
private func registerAPIRoutes(on routes: RoutesBuilder, app: Application) {
    // Tighter limit for endpoints that mutate Redis state — the app API key is
    // embedded in every binary and extractable, so a leaked key shouldn't be
    // able to flood Redis with garbage registrations.
    let writeRoutes = routes.grouped(RateLimitMiddleware(limit: 20, windowSeconds: 60, keyPrefix: "rl:write"))

    // MARK: - Client Telemetry
    // Lightweight ingestion for client-side funnel events (paywall_shown,
    // gate_hit, purchase_completed, activation_*). Namespaced `client.<event>` and
    // fed into the same Telemetry composite as server events, so they land in the
    // Redis per-day counters (admin-viewable) and structured logs for free.
    // Fail-open by construction: a malformed body, unknown event, or oversized
    // field must never surface an error to the client's fire-and-forget call.
    // Mounted on `routes` (300/min) rather than `writeRoutes` (20/min) because
    // these are user-paced and higher-frequency than registrations.
    routes.post("telemetry") { req async throws -> HTTPStatus in
        guard let payload = try? req.content.decode(ClientTelemetryEvent.self),
              ClientTelemetryEvent.allowedEvents.contains(payload.event) else {
            return .ok
        }
        // Bound field cardinality/size so a leaked key can't bloat log/counter keys.
        var fields = (payload.fields ?? [:]).filter { $0.key.count <= 32 && $0.value.count <= 64 }
        if let install = req.headers.first(name: "X-Install-ID") {
            fields["install"] = String(install.prefix(8))
        }
        await req.telemetry.info("client.\(payload.event)", fields)
        return .ok
    }

    //MARK: - Schedules
    // The schedule is already stored in Redis as JSON (written via setJSON). Return
    // the cached string verbatim instead of decoding it into a LiveScore and
    // re-encoding it on every request — that round-trip burned ~5s of CPU per call
    // (the dominant TTFB cost) and is pure waste since the bytes are identical.
    routes.get("schedules") { req async throws -> String in
        let key = RedisEndpoint.ESPN.latestSchedule.getValue(isDebug: req.application.environment == .development).rawValue
        guard let raw = try await req.kv.getString(key), !raw.isEmpty else {
            throw NetworkError.invalidData
        }
        return raw
    }

    //MARK: - Sport
    routes.get("sport", ":sport") { req in
        let sport = SportType(rawValue: req.parameters.get("sport")!)
        let schedule = try await req.kv.getJSON(RedisEndpoint.ESPN.latestSchedule.getValue(isDebug: req.application.environment == .development).rawValue, as: LiveScore.self)
        let result: LiveEvent?
        switch sport {
        case .basketball:
            guard let nba = schedule?.nba else { throw Abort(.badRequest) }
            result = nba
        case .soccer:
            guard let soccer = schedule?.soccer else { throw Abort(.badRequest) }
            result = soccer
        case .hockey:
            guard let nhl = schedule?.nhl else { throw Abort(.badRequest) }
            result = nhl
        case .mlb:
            guard let mlb = schedule?.mlb else { throw Abort(.badRequest) }
            result = mlb
        case .nfl:
            guard let nfl = schedule?.nfl else { throw Abort(.badRequest) }
            result = nfl
        case .golf:
            guard let golf = schedule?.golf else { throw Abort(.badRequest) }
            result = golf
        case .tennis:
            guard let tennis = schedule?.tennis else { throw Abort(.badRequest) }
            result = tennis
        case .racing:
            guard let racing = schedule?.racing else { throw Abort(.badRequest) }
            result = racing
        case .none:
            throw Abort(.badRequest)
        }
        if let res = result {
            return encodeResult(res: res)
        } else {
            throw Abort(.badRequest)
        }
    }

    //MARK: - On-demand schedule for a specific day
    // The cached /schedules blob only spans the recent/upcoming window. This
    // endpoint fetches every ESPN league's scoreboard for an arbitrary day
    // (path param `date` = YYYYMMDD) and returns a merged LiveScore, so the
    // client can browse multi-sport schedules far outside that window. Results
    // are cached per-day (past days are immutable → long TTL).
    routes.get("schedules", "date", ":date") { req async throws -> String in
        guard let dateStr = req.parameters.get("date"),
              dateStr.count == 8, let dateInt = Int(dateStr) else {
            throw Abort(.badRequest)
        }
        let isDebug = req.application.environment == .development
        let cacheKey = "ESPN Schedule Date \(dateInt)\(isDebug ? " DEBUG" : "")"
        if let cached = try? await req.kv.getString(cacheKey), !cached.isEmpty {
            return cached
        }
        let liveScore = await buildESPNScheduleForDate(dateInt: dateInt, client: req.client)
        let json = encodeResult(res: liveScore)

        let fmt = DateFormatter()
        fmt.dateFormat = "yyyyMMdd"
        fmt.timeZone = TimeZone(identifier: "America/New_York")
        let todayInt = Int(fmt.string(from: Date())) ?? dateInt
        let ttl: TimeInterval = dateInt < todayInt ? 86_400 : 600
        try? await req.kv.setString(cacheKey, value: json, ttl: ttl)
        return json
    }

    //MARK: - Teams
    // Same as /schedules: serve the cached JSON string directly rather than
    // decoding to [Team] and re-encoding it per request.
    routes.get("teams") { req async throws -> String in
        let key = RedisEndpoint.teams.getValue(isDebug: req.application.environment == .development).rawValue
        do {
            let value = (try await req.kv.getString(key)) ?? "[]"
            // Only cache real payloads — never let an empty result poison the
            // fallback (that would re-create the "no teams" failure mode).
            if value != "[]" { await LastKnownGoodCache.shared.storeTeams(value) }
            return value
        } catch {
            if let cached = await LastKnownGoodCache.shared.teamsValue {
                req.logger.warning("teams: Redis read failed, serving last-known-good — \(String(reflecting: error))")
                return cached
            }
            throw error
        }
    }

    //MARK: - Play-by-Play (per-event)
    // Three-tier lookup: (1) Redis hot cache for live/in-progress games, (2) SQLite archive
    // for finalized games, (3) on-demand ESPN fetch using the `ESPN-Event-Map` or query params.
    routes.get("plays", ":eventID") { req async throws -> String in
        guard let eventID = req.parameters.get("eventID"), !eventID.isEmpty else {
            throw Abort(.badRequest)
        }
        let sport = try? req.query.get(String.self, at: "sport")
        let league = try? req.query.get(String.self, at: "league")
        guard let cached = try await PlayResolver.resolve(
            req: req, eventID: eventID, sport: sport, league: league
        ) else {
            throw Abort(.notFound)
        }
        return encodeResult(res: cached)
    }

    //MARK: - Live Websocket
    routes.webSocket("ws") { req, ws async in
        let isDebug = req.application.environment == .development
        var lastSentHash: Int? = nil

        while !ws.isClosed {
            do {
                // Check if there are live or upcoming games before pushing data
                let hasGames = await Integrator.hasLiveOrUpcomingGames(
                    redis: req.application.redis,
                    isDebug: isDebug
                )

                if hasGames {
                    // Serve the cached JSON string verbatim instead of decoding to
                    // LiveScore and re-encoding it — same waste the /schedules fix
                    // removed, but here it ran every 5s per connected client. The
                    // stored bytes are identical to what encodeResult would produce.
                    let key = RedisEndpoint.ESPN.latestLiveInfo.getValue(isDebug: isDebug).rawValue
                    let stringResult = (try await req.kv.getString(key)) ?? "{}"

                    // Only send if data actually changed (avoids redundant multi-MB pushes)
                    let currentHash = stringResult.hashValue
                    if currentHash != lastSentHash {
                        // Observability: the live frame outgrew the old 4 MB client
                        // cap (~4.76 MB seen). WebSocket frames bypass Caddy's gzip,
                        // so they ship uncompressed — log the size to track the
                        // culprit and confirm it stays within the client's 16 MB cap.
                        let bytes = stringResult.utf8.count
                        if bytes > 3_000_000 {
                            req.logger.warning("Large live WS frame", metadata: ["bytes": "\(bytes)"])
                        }
                        try await ws.send(stringResult)
                        lastSentHash = currentHash
                    }

                    try await Task.sleep(nanoseconds: 5_000_000_000) // 5s when live
                } else {
                    // No live games — sleep longer and send lightweight heartbeat
                    lastSentHash = nil
                    try await ws.send("{}")
                    try await Task.sleep(nanoseconds: 60_000_000_000) // 60s when idle
                }
            } catch {
                req.logger.error("WebSocket live score push failed", metadata: ["error": "\(error)"])
                break
            }
        }
    }

    //MARK: - all-live-games
    routes.get("all-live-games") { req async throws -> String in
        let liveScore = try await req.kv.getJSON(RedisEndpoint.ESPN.latestFullLiveInfo.getValue(isDebug: req.application.environment == .development).rawValue, as: LiveScore.self)
        return encodeResult(res: liveScore)
    }

    //MARK: DEBUG
    if app.environment == .development {
        //MARK: - livedebug websocket
        routes.webSocket("livedebug") { req, ws async in
            while !ws.isClosed {
                do {
                    var directory = req.application.directory.workingDirectory
                    directory.append("/LiveTest.json")
                    let fileURL = URL(fileURLWithPath: directory)
                    var jsonScore = try JSONDecoder().decode(LiveScore.self, from: Data(contentsOf: fileURL))
                    
                    
                    let newEvents: [Game] = jsonScore.soccer?.events
                        .compactMap({ game -> Game in
                            let newHomeScore = "\(Int.random(in: 1...5))"
                            let newAwayScore = "\(Int.random(in: 1...5))"
                            // Only include essential fields - strSport/strLeague are computed from idLeague
                            return Game(idLiveScore: game.idLiveScore, idEvent: game.idEvent, strSport: nil, idLeague: game.idLeague, strLeague: nil, idHomeTeam: game.idHomeTeam, idAwayTeam: game.idAwayTeam, strHomeTeam: game.strHomeTeam, strAwayTeam: game.strAwayTeam, strHomeTeamBadge: game.strHomeTeamBadge, strAwayTeamBadge: game.strAwayTeamBadge, intHomeScore: newHomeScore, intAwayScore: newAwayScore, strPlayer: nil, idPlayer: nil, intEventScore: nil, intEventScoreTotal: nil, strStatus: game.strStatus, strProgress: game.strProgress, strEventTime: nil, dateEvent: nil, updated: nil, strTimestamp: game.strTimestamp, isoDate: nil)

                        }) ?? []
                    jsonScore.soccer?.events = newEvents
                    try await Task.sleep(nanoseconds: 5000000000)
                    let stringResult = encodeResult(res: jsonScore)
                    try await ws.send(stringResult)
                } catch {
                    req.logger.error("Debug WebSocket live score push failed", metadata: ["error": "\(error)"])
                }
            }
        }

        //MARK: - replay (developer "replay a game as live")
        // The client connects, sends the selected `Game` shell as the first text frame,
        // and the server streams reconstructed `LiveScore` frames from that game's recorded
        // play-by-play, paced by `?speed=` (frames-per-second, default 8). Dev-only.
        // maxFrameSize is bumped well past the 16 KB default: the client's first frame carries
        // the full play-by-play array (often 100 KB–1 MB), which the default would reject.
        routes.webSocket("replay", ":eventID", maxFrameSize: .init(integerLiteral: 8 * 1024 * 1024)) { req, ws async in
            let eventID = req.parameters.get("eventID") ?? ""
            let speed = min(max((try? req.query.get(Double.self, at: "speed")) ?? 8.0, 0.1), 5000)

            // Await the game shell (first inbound text frame), with a timeout fallback so a
            // silent client doesn't leak the connection. The async `webSocket` closure runs in a
            // detached Task (off the connection's event loop), but `ws.onText`'s setter is guarded
            // by `preconditionInEventLoop()` — so we must register it on `ws.eventLoop`. Registering
            // onText + scheduleTask on the same loop also keeps the `fired` guard race-free.
            final class Once { var fired = false }
            let once = Once()
            let shellText: String? = await withCheckedContinuation { (cont: CheckedContinuation<String?, Never>) in
                ws.eventLoop.execute {
                    ws.onText { _, text in
                        guard !once.fired else { return }
                        once.fired = true
                        cont.resume(returning: text)
                    }
                    ws.eventLoop.scheduleTask(in: .seconds(15)) {
                        guard !once.fired else { return }
                        once.fired = true
                        cont.resume(returning: nil)
                    }
                }
            }

            // The handshake carries the shell and (optionally) client-fetched plays. Fall back
            // to a bare `Game` for older clients.
            let handshake: ReplayHandshake?
            let shell: Game?
            if let shellText, let shellData = shellText.data(using: .utf8) {
                handshake = try? JSONDecoder().decode(ReplayHandshake.self, from: shellData)
                shell = handshake?.shell ?? (try? JSONDecoder().decode(Game.self, from: shellData))
            } else {
                handshake = nil
                shell = nil
            }
            guard let shell, let slot = ReplayDriver.slot(for: shell) else {
                try? await ws.send(#"{"error":"replay: missing or unsupported game shell"}"#)
                try? await ws.close()
                return
            }

            // Prefer client-supplied plays; otherwise resolve them server-side.
            var plays = handshake?.plays ?? []
            if plays.isEmpty {
                let espn = ReplayDriver.espnSportLeague(for: shell)
                plays = (try? await PlayResolver.resolve(
                    req: req, eventID: eventID, sport: espn?.sport, league: espn?.league
                ))?.plays ?? []
            }
            guard !plays.isEmpty else {
                try? await ws.send(#"{"error":"replay: no play-by-play available for this game"}"#)
                try? await ws.close()
                return
            }

            req.logger.info("Replay starting for \(eventID): \(plays.count) plays at \(speed)x")
            let frames = ReplayDriver.snapshots(shell: shell, plays: plays, slot: slot)
            let delayNanos = UInt64((1_000_000_000.0 / speed).rounded())
            for frame in frames {
                if ws.isClosed { break }
                try? await ws.send(encodeResult(res: frame))
                try? await Task.sleep(nanoseconds: delayNanos)
            }
            req.logger.info("Replay finished for \(eventID)")
        }

        //MARK: - live-debug
        routes.get("live-debug") { req async throws in
            var directory = req.application.directory.workingDirectory
            directory.append("/MockLive.json")
            let fileURL = URL(fileURLWithPath: directory)
            let jsonScore = try JSONDecoder().decode(LiveScore.self, from: Data(contentsOf: fileURL))
            let stringResult = encodeResult(res: jsonScore)
            return stringResult
        }

        //MARK: - Debug Push-to-Start Trigger
        routes.post("debug", "trigger-push-to-start") { req async throws -> String in
            struct DebugTriggerRequest: Content {
                var eventID: String
                var homeTeam: String
                var awayTeam: String
            }

            let body = try req.content.decode(DebugTriggerRequest.self)
            let apnsConfigured = req.application.storage[APNSConfiguredKey.self] ?? false

            // Iterate both prod and sandbox install keyspaces so a single dev
            // server can dispatch tests to both Xcode dev devices and TestFlight
            // tokens.
            let envSpecs: [(prefix: String, env: APNSEnvironment)] = [
                ("PushToStartByInstall-", .production),
                ("debug-PushToStartByInstall-", .sandbox),
            ]

            // Build diagnostic trace
            var trace: [String] = []
            trace.append("env=\(req.application.environment.name)")
            trace.append("apnsConfigured=\(apnsConfigured)")
            trace.append("triggerEventID=\(body.eventID)")
            trace.append("triggerHome=\(body.homeTeam)")
            trace.append("triggerAway=\(body.awayTeam)")

            var allInstalls: [(install: PushToStartInstall, env: APNSEnvironment)] = []
            for spec in envSpecs {
                let pattern = "\(spec.prefix)*"
                let scanned = (try? await req.application.redis.send(command: "keys", with: [pattern.convertedToRESPValue()])
                    .array?
                    .compactMap({ $0.string })) ?? []
                trace.append("\(spec.env.rawValue) installs=\(scanned.count)")
                for key in scanned {
                    if let install = try? await req.kv.getJSON(key, as: PushToStartInstall.self) {
                        allInstalls.append((install, spec.env))
                    }
                }
            }
            trace.append("totalInstalls=\(allInstalls.count)")

            guard !allInstalls.isEmpty else {
                let traceStr = trace.joined(separator: "\n")
                let result: [String: Any] = ["notified": 0, "tokens": [] as [String], "reason": "no_registrations", "trace": traceStr]
                let data = try JSONSerialization.data(withJSONObject: result)
                return String(data: data, encoding: .utf8)!
            }

            guard apnsConfigured else {
                let traceStr = trace.joined(separator: "\n")
                let result: [String: Any] = ["notified": 0, "tokens": [] as [String], "reason": "apns_not_configured", "trace": traceStr]
                let data = try JSONSerialization.data(withJSONObject: result)
                return String(data: data, encoding: .utf8)!
            }

            let prodClient = await req.application.apns.client(.production)
            let sandboxClient = await req.application.apns.client(.development)
            var notifiedTokens: [String] = []
            var errors: [String] = []

            for entry in allInstalls {
                let install = entry.install
                let token = install.token

                let favoritesMatch = install.favorites.contains(where: { $0 == body.homeTeam || $0 == body.awayTeam })
                let eventMatch = install.eventIDs.contains(body.eventID)

                trace.append("install=\(install.installID.prefix(8))... token=\(token.prefix(12))... [\(entry.env.rawValue)] favorites=\(install.favorites) eventIDs=\(install.eventIDs) favMatch=\(favoritesMatch) eventMatch=\(eventMatch)")

                guard favoritesMatch || eventMatch else { continue }

                let attributes = LiveSportAttributes(
                    homeTeam: body.homeTeam,
                    awayTeam: body.awayTeam,
                    eventID: body.eventID
                )
                let contentState = ContentState(
                    homeScore: 12,
                    awayScore: 9,
                    status: "in",
                    progress: "4:20 - 1st",
                    lastPlay: nil
                )

                do {
                    let notification = APNSStartLiveActivityNotification(
                        expiration: .immediately,
                        priority: .immediately,
                        appID: "com.KomodoLLC.SportsCal",
                        contentState: contentState,
                        timestamp: Int(Date().timeIntervalSince1970),
                        attributes: attributes,
                        attributesType: "LiveSportActivityAttributes",
                        alert: APNSAlertNotificationContent(
                            title: .raw("\(body.homeTeam) vs \(body.awayTeam)"),
                            body: .raw("Debug game is starting now!")
                        )
                    )
                    let client = entry.env == .sandbox ? sandboxClient : prodClient
                    try await client.sendStartLiveActivityNotification(
                        notification,
                        deviceToken: token,
                        collapseID: body.eventID
                    )
                    notifiedTokens.append(String(token.prefix(12)) + "...")
                    trace.append("SENT OK to \(token.prefix(12))... [\(entry.env.rawValue)]")
                } catch {
                    let errMsg = "\(error)"
                    errors.append("\(token.prefix(12))... [\(entry.env.rawValue)]: \(errMsg)")
                    trace.append("SEND FAILED \(token.prefix(12))... [\(entry.env.rawValue)]: \(errMsg)")
                    if let apnsError = error as? APNSError,
                       apnsError.reason == .badDeviceToken || apnsError.reason == .unregistered {
                        let isSandbox = entry.env == .sandbox
                        let installKey = RedisEndpoint.pushToStartByInstall(install.installID).getValue(isDebug: isSandbox).rawValue
                        let indexKey = RedisEndpoint.pushToStartTokenIndex(token).getValue(isDebug: isSandbox).rawValue
                        _ = try? await req.kv.delete([installKey, indexKey])
                        trace.append("Removed stale install \(install.installID.prefix(8))... [\(entry.env.rawValue)]")
                    }
                }
            }

            let traceStr = trace.joined(separator: "\n")
            var result: [String: Any] = [
                "notified": notifiedTokens.count,
                "tokens": notifiedTokens,
                "trace": traceStr
            ]
            if !errors.isEmpty { result["errors"] = errors }
            if notifiedTokens.isEmpty && allInstalls.count > 0 {
                result["reason"] = "no_match"
            }
            let data = try JSONSerialization.data(withJSONObject: result)
            return String(data: data, encoding: .utf8)!
        }

    }

    //MARK: - live
    routes.get("live") { req async throws in
        var result = try await req.kv.getJSON(RedisEndpoint.ESPN.latestLiveInfo.getValue(isDebug: req.application.environment == .development).rawValue, as: LiveScore.self)
        result?.removeNonStarting()
//        result?.removeOtherInfo()
        return encodeResult(res: result)
    }

    //MARK: - liveActivity
    writeRoutes.post("liveActivity") { req async throws -> HTTPStatus in
        let body = try req.content.decode(LiveActivityRegistration.self)
        let environment = resolveAPNSEnvironment(from: req)
        let registration = APNSRegistration(
            eventID: body.eventID,
            homeTeam: body.homeTeam,
            awayTeam: body.awayTeam,
            environment: environment
        )
        let key = (environment == .sandbox ? "debug-APNS-" : "APNS-") + body.token
        // 12h matches the iOS Live Activity max lifetime; APNSJob slides this forward
        // on every successful update so an active activity never expires mid-game.
        try await req.kv.setJSON(key, value: registration, ttl: 60 * 60 * 12)
        return .ok
    }

    // Counterpart to the POST: drop the per-activity registration on the host
    // the iOS client just left so APNSJob there stops dispatching updates. Used
    // by the iOS env-flip handler — without this, two servers' Redis instances
    // can each retain registrations for the same install and both will try to
    // push, spawning duplicate Live Activities.
    writeRoutes.delete("liveActivity") { req async throws -> HTTPStatus in
        let body = try req.content.decode(DeregisterRequest.self)
        let environment = resolveAPNSEnvironment(from: req)
        let key = (environment == .sandbox ? "debug-APNS-" : "APNS-") + body.token
        _ = try await req.kv.delete([key])
        return .ok
    }

    //MARK: - livescore/sport
    routes.webSocket("livescore",":sport") { req, ws async in
        let sport = SportType(rawValue: req.parameters.get("sport")!)
        do {
            switch sport {
            case .basketball:
                let basketball: LiveEvent? = try await SportsDBNetworking.callLiveScore(req: req.client, DecodeType: LiveEvent.self, scoreType: .basketball)
                let result = LiveScore(nba: basketball)
                let stringData = encodeResult(res: result)
                try await ws.send(stringData)
            case .soccer:
                let soccer: LiveEvent? = try await SportsDBNetworking.callLiveScore(req: req.client, DecodeType: LiveEvent.self, scoreType: .soccer)
                let result = LiveScore(soccer: soccer)
                let stringData = encodeResult(res: result)
                try await ws.send(stringData)
            case .hockey:
                let hockey: LiveEvent? = try await SportsDBNetworking.callLiveScore(req: req.client, DecodeType: LiveEvent.self, scoreType: .hockey)
                let result = LiveScore(nhl: hockey)
                let stringData = encodeResult(res: result)
                try await ws.send(stringData)
            case .nfl:
                let mlb: LiveEvent? = try await SportsDBNetworking.callLiveScore(req: req.client, DecodeType: LiveEvent.self, scoreType: .mlb)
                let result = LiveScore(mlb: mlb)
                let stringData = encodeResult(res: result)
                try await ws.send(stringData)
            case .mlb:
                let nfl: LiveEvent? = try await SportsDBNetworking.callLiveScore(req: req.client, DecodeType: LiveEvent.self, scoreType: .nfl)
                let result = LiveScore(nfl: nfl)
                let stringData = encodeResult(res: result)
                try await ws.send(stringData)
            case .golf:
                let golf: LiveEvent? = try await SportsDBNetworking.callLiveScore(req: req.client, DecodeType: LiveEvent.self, scoreType: .golf)
                let result = LiveScore(golf: golf)
                let stringData = encodeResult(res: result)
                try await ws.send(stringData)
            case .tennis:
                let tennis: LiveEvent? = try await SportsDBNetworking.callLiveScore(req: req.client, DecodeType: LiveEvent.self, scoreType: .tennis)
                let result = LiveScore(tennis: tennis)
                let stringData = encodeResult(res: result)
                try await ws.send(stringData)
            case .racing:
                let racing: LiveEvent? = try await SportsDBNetworking.callLiveScore(req: req.client, DecodeType: LiveEvent.self, scoreType: .motorsport)
                let result = LiveScore(racing: racing)
                let stringData = encodeResult(res: result)
                try await ws.send(stringData)
            case .none:
                req.logger.warning("livescore WebSocket called with invalid sport")
            }
        } catch {
            req.logger.error("livescore WebSocket failed", metadata: [
                "sport": "\(sport?.rawValue ?? "nil")",
                "error": "\(error)"
            ])
        }

    }

    //MARK: - test-call
    routes.get("test-call") { req async in
        req.logger.info("test-call endpoint hit")
        return "Welcome to sportscal! BG task call"
    }

    //MARK: - World Cup
    // Knockout bracket (built by WorldCupEnrichmentJob, cached in Redis).
    routes.get("worldcup", "bracket") { req async throws -> String in
        let isDebug = req.application.environment == .development
        let key = RedisEndpoint.ESPN.worldCupBracket.getValue(isDebug: isDebug)
        let bracket = (try? await req.application.redis.get(key, asJSON: WorldCupBracket.self)) ?? WorldCupBracket()
        return encodeResult(res: bracket)
    }

    // Golden Boot / top scorers (cached in Redis).
    routes.get("worldcup", "scorers") { req async throws -> String in
        let isDebug = req.application.environment == .development
        let key = RedisEndpoint.ESPN.worldCupScorers.getValue(isDebug: isDebug)
        let scorers = (try? await req.application.redis.get(key, asJSON: [WorldCupScorer].self)) ?? []
        return encodeResult(res: scorers)
    }

    // Squad for a national team — fetched lazily from ESPN and cached 24h.
    routes.get("worldcup", "squad", ":teamID") { req async throws -> String in
        guard let teamID = req.parameters.get("teamID"), !teamID.isEmpty else {
            throw Abort(.badRequest)
        }
        let isDebug = req.application.environment == .development
        let cacheKey: RedisKey = isDebug ? "debug-World Cup Squad-\(teamID)" : "World Cup Squad-\(teamID)"
        if let cached = try? await req.application.redis.get(cacheKey, asJSON: WorldCupSquad.self) {
            return encodeResult(res: cached)
        }
        let roster = try await ESPNNetworking.getRoster(req: req.client, league: .FIFA_World_Cup, teamID: teamID)
        let squad = WorldCupSquad(
            teamID: roster.team?.id ?? teamID,
            teamName: roster.team?.displayName ?? "",
            teamBadge: roster.team?.logos?.first?.href,
            players: roster.flatAthletes
        )
        if !squad.players.isEmpty {
            try? await req.application.redis.setex(cacheKey, toJSON: squad, expirationInSeconds: 60 * 60 * 24).get()
        }
        return encodeResult(res: squad)
    }

    // Per-match box score (team stats, lineups, goal/card/sub timeline) — fetched
    // lazily from ESPN's per-event summary and cached briefly so a live match stays
    // fresh while finals aren't re-fetched on every detail open. Returns 404 when ESPN
    // has no box score yet (pre-match), which the client treats as "not available".
    routes.get("worldcup", "boxscore", ":eventID") { req async throws -> String in
        guard let eventID = req.parameters.get("eventID"), !eventID.isEmpty else {
            throw Abort(.badRequest)
        }
        let isDebug = req.application.environment == .development
        let cacheKey: RedisKey = isDebug ? "debug-World Cup BoxScore-\(eventID)" : "World Cup BoxScore-\(eventID)"
        if let cached = try? await req.application.redis.get(cacheKey, asJSON: WorldCupBoxScore.self) {
            return encodeResult(res: cached)
        }
        let summary = try await ESPNNetworking.getSoccerSummary(req: req.client, league: .FIFA_World_Cup, eventId: eventID)
        guard let box = WorldCupBoxScoreBuilder.build(from: summary, eventID: eventID) else {
            throw Abort(.notFound)
        }
        // 90s TTL: short enough to track a live match, long enough to absorb repeat opens.
        try? await req.application.redis.setex(cacheKey, toJSON: box, expirationInSeconds: 90).get()
        return encodeResult(res: box)
    }

    //MARK: - Standings
    routes.get("standings", ":leagueID") { req async throws -> String in
        guard let leagueIDString = req.parameters.get("leagueID"),
              let leagueID = Int(leagueIDString),
              let league = Leagues(rawValue: leagueID) else {
            throw Abort(.badRequest)
        }
        let standingsResponse = try await ESPNNetworking.getStandings(req: req.client, DecodeType: StandingsResponse.self, league: league)
        let standing = Standing(id: league, standings: standingsResponse)
        return encodeResult(res: standing)
    }

    //MARK: - Standings History
    routes.get("standings", ":leagueID", "history") { req async throws -> String in
        guard let leagueIDString = req.parameters.get("leagueID"),
              let leagueID = Int(leagueIDString),
              let _ = Leagues(rawValue: leagueID) else {
            throw Abort(.badRequest)
        }
        let days = (try? req.query.get(Int.self, at: "days")) ?? 30
        let isDebug = req.application.environment == .development

        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy-MM-dd"
        formatter.timeZone = TimeZone(identifier: "UTC")

        var snapshots: [StandingsSnapshot] = []
        let today = Date()

        for dayOffset in 0..<min(days, 90) {
            guard let date = Calendar.current.date(byAdding: .day, value: -dayOffset, to: today) else { continue }
            let dateStr = formatter.string(from: date)
            let key: RedisKey = isDebug
                ? "debug-Standings-\(leagueID)-\(dateStr)"
                : "Standings-\(leagueID)-\(dateStr)"

            if let json = try await req.application.redis.get(key, as: String.self).get(),
               let data = json.data(using: .utf8),
               let snapshot = try? JSONDecoder().decode(StandingsSnapshot.self, from: data) {
                snapshots.append(snapshot)
            }
        }

        snapshots.sort { $0.date < $1.date }
        let encoder = JSONEncoder()
        let data = try encoder.encode(snapshots)
        return String(data: data, encoding: .utf8) ?? "[]"
    }

    //MARK: - Team Stats
    routes.get("stats", ":leagueID", "teams") { req async throws -> String in
        guard let leagueIDString = req.parameters.get("leagueID"),
              let leagueID = Int(leagueIDString),
              let league = Leagues(rawValue: leagueID) else {
            throw Abort(.badRequest)
        }
        let standingsResponse = try await ESPNNetworking.getStandings(
            req: req.client,
            DecodeType: StandingsResponse.self,
            league: league
        )

        // Reshape standings entries into team stat objects
        var teamStats: [[String: Any]] = []
        if let children = standingsResponse.children {
            for child in children {
                guard let entries = child.standings?.entries else { continue }
                for entry in entries {
                    var statDict: [String: String] = [:]
                    for stat in entry.stats ?? [] {
                        if let name = stat.name, let value = stat.displayValue {
                            statDict[name] = value
                        }
                    }
                    let teamObj: [String: Any] = [
                        "teamName": entry.team?.displayName ?? "Unknown",
                        "teamAbbreviation": entry.team?.abbreviation ?? "",
                        "teamColor": entry.team?.color ?? "",
                        "teamLogo": entry.team?.logos?.first?.href ?? "",
                        "division": child.name ?? "",
                        "stats": statDict
                    ]
                    teamStats.append(teamObj)
                }
            }
        }

        let data = try JSONSerialization.data(withJSONObject: teamStats)
        return String(data: data, encoding: .utf8) ?? "[]"
    }

    //MARK: - Player Stats (Stat Leaders)
    routes.get("stats", ":leagueID", "players") { req async throws -> String in
        guard let leagueIDString = req.parameters.get("leagueID"),
              let leagueID = Int(leagueIDString),
              let league = Leagues(rawValue: leagueID) else {
            throw Abort(.badRequest)
        }

        let isDebug = req.application.environment == .development
        let cacheKey = "PlayerStats-\(leagueID)"

        // Check Redis cache first (24h TTL)
        if let cached = try? await req.application.redis.get(RedisKey(cacheKey), as: String.self).get() {
            return cached
        }

        let leadersResponse = try await ESPNNetworking.getLeaders(
            req: req.client,
            DecodeType: LeadersResponse.self,
            league: league
        )

        var categories: [[String: Any]] = []
        for category in leadersResponse.leaders ?? [] {
            var entries: [[String: Any]] = []
            for leader in category.leaders ?? [] {
                var entry: [String: Any] = [
                    "value": leader.displayValue ?? ""
                ]
                if let athlete = leader.athlete {
                    entry["playerName"] = athlete.displayName ?? ""
                    entry["shortName"] = athlete.shortName ?? ""
                    entry["headshot"] = athlete.headshot?.href ?? ""
                    entry["position"] = athlete.position?.abbreviation ?? ""
                }
                if let team = leader.team {
                    entry["teamName"] = team.displayName ?? ""
                    entry["teamAbbreviation"] = team.abbreviation ?? ""
                    entry["teamColor"] = team.color ?? ""
                    entry["teamLogo"] = team.logos?.first?.href ?? ""
                }
                entries.append(entry)
            }
            categories.append([
                "name": category.name ?? "",
                "displayName": category.displayName ?? "",
                "abbreviation": category.abbreviation ?? "",
                "leaders": entries
            ])
        }

        let data = try JSONSerialization.data(withJSONObject: categories)
        let result = String(data: data, encoding: .utf8) ?? "[]"

        // Cache for 24 hours
        try? await req.application.redis.setex(RedisKey(cacheKey), to: result, expirationInSeconds: 60 * 60 * 24)

        return result
    }

    //MARK: - Push-to-Start Registration (install-ID keyed)
    //
    // One Redis record per install. APNS token rotation just overwrites the
    // install's record — no orphan keys can shadow the new token. Per the
    // historical bug: previously each `PushToStart-{token}` and
    // `PushToStartEvents-{token}` could outlive a rotated token for 24h and
    // both the old and new tokens would receive push-to-start for the same
    // game, spawning two Live Activities on the device.
    writeRoutes.post("pushToStart", "register") { req async throws -> HTTPStatus in
        let registration = try req.content.decode(PushToStartRegistration.self)
        let environment = resolveAPNSEnvironment(from: req)
        let isSandbox = environment == .sandbox
        let installID = resolveInstallID(from: req, fallbackToken: registration.token)

        let install = PushToStartInstall(
            installID: installID,
            token: registration.token,
            favorites: registration.favorites,
            eventIDs: registration.eventIDs ?? [],
            environment: environment
        )

        // If this install previously held a different token, drop the reverse
        // index pointing at it so a stale-token cleanup later won't blow away
        // the live install.
        let installKey = RedisEndpoint.pushToStartByInstall(installID).getValue(isDebug: isSandbox).rawValue
        if let existing = try? await req.kv.getJSON(installKey, as: PushToStartInstall.self),
           existing.token != registration.token {
            let staleIndex = RedisEndpoint.pushToStartTokenIndex(existing.token).getValue(isDebug: isSandbox).rawValue
            _ = try? await req.kv.delete([staleIndex])
            // Same install, new token → ActivityKit rotated the push-to-start token.
            // Surface it so we can watch rotation frequency (it determines how often
            // a long-TTL registration would otherwise go stale before a refresh).
            req.logger.info("Push-to-start token rotated for install \(installID.prefix(8))... [\(environment.rawValue)] (\(existing.token.prefix(8))... → \(registration.token.prefix(8))...)")
            await req.telemetry.warning("pushtostart.token_rotated", [
                "install": String(installID.prefix(8)),
                "env": environment.rawValue,
            ])
        }

        let indexKey = RedisEndpoint.pushToStartTokenIndex(registration.token).getValue(isDebug: isSandbox).rawValue
        do {
            try await req.kv.setJSON(installKey, value: install, ttl: PushToStartInstall.registrationTTL)
            try await req.kv.setString(indexKey, value: installID, ttl: PushToStartInstall.registrationTTL)
        } catch {
            // Capture before rethrowing: a failed persist here means the device
            // can never receive a push-to-start, and it used to vanish silently.
            await req.telemetry.error("pushtostart.register.failed", [
                "install": String(installID.prefix(8)),
                "env": environment.rawValue,
                "error": "\(error)",
            ])
            throw error
        }

        req.logger.info("Registered push-to-start install \(installID.prefix(8))... [\(environment.rawValue)] favorites=\(registration.favorites.count) eventIDs=\(install.eventIDs.count)")
        await req.telemetry.info("pushtostart.registered", [
            "install": String(installID.prefix(8)),
            "env": environment.rawValue,
            "favorites": "\(registration.favorites.count)",
            "events": "\(install.eventIDs.count)",
        ])

        // Push-to-start is otherwise transition-only: the scheduled job fires when a
        // game flips to "in". A user who follows a match that is ALREADY live (or
        // taps "Follow World Cup" mid-match) would get nothing until the next
        // kickoff. Kick off Live Activities for any followed games that are live
        // right now. Deduped against the transition path via the shared
        // SentPushToStart-{token}-{eventID} claim, so this never double-fires.
        if req.application.storage[APNSConfiguredKey.self] == true {
            let serverIsDebug = req.application.environment == .development
            let liveKey = RedisEndpoint.ESPN.latestLiveInfo.getValue(isDebug: serverIsDebug).rawValue
            if let liveScore = try? await req.kv.getJSON(liveKey, as: LiveScore.self) {
                await ESPNFetchJob.sendStartsForAlreadyLiveGames(
                    install: install,
                    liveGames: ESPNFetchJob.collectAllGamesFromLiveScore(liveScore),
                    environment: environment,
                    kv: req.kv,
                    apns: req.application.apnsSending,
                    clock: req.application.appClock,
                    isDebug: serverIsDebug,
                    logger: req.logger,
                    metrics: req.application.pushMetrics,
                    telemetry: req.application.telemetry
                )
            }
        }
        return .ok
    }

    // Counterpart to the POST: drops the install's record plus its reverse
    // index and any lingering per-event SentPushToStart markers.
    writeRoutes.delete("pushToStart", "register") { req async throws -> HTTPStatus in
        let body = try req.content.decode(DeregisterRequest.self)
        let environment = resolveAPNSEnvironment(from: req)
        let isSandbox = environment == .sandbox
        let installID = resolveInstallID(from: req, fallbackToken: body.token)

        let installKey = RedisEndpoint.pushToStartByInstall(installID).getValue(isDebug: isSandbox).rawValue
        let indexKey = RedisEndpoint.pushToStartTokenIndex(body.token).getValue(isDebug: isSandbox).rawValue
        var keysToDelete = [installKey, indexKey]
        // SentPushToStart-{token}-{eventID} markers are per-event; scan to find them all.
        let sentPattern = (isSandbox ? "debug-SentPushToStart-" : "SentPushToStart-") + body.token + "-*"
        let sentKeys = (try? await req.kv.scanKeys(matching: sentPattern)) ?? []
        keysToDelete.append(contentsOf: sentKeys)
        let deleted = (try? await req.kv.delete(keysToDelete)) ?? 0
        req.logger.info("Deregistered push-to-start install \(installID.prefix(8))... [\(environment.rawValue)] — removed \(deleted) keys (\(sentKeys.count) sent-markers)")
        return .ok
    }

    //MARK: - teams-by-league
    routes.get("teams-by-league") { req async throws -> String in
        let result = try await req.application.redis.get(RedisEndpoint.ESPN.teams.getValue(isDebug: req.application.environment == .development), asJSON: [Leagues: TeamResponse].self)
        return encodeResult(res: result)
    }

    //MARK: - Widget Schedule (lightweight combined endpoint)
    routes.get("widget", "schedule") { req async throws -> String in
        let sportsParam = (try? req.query.get(String.self, at: "sports")) ?? ""
        let limit = (try? req.query.get(Int.self, at: "limit")) ?? 6
        let favoritesParam = (try? req.query.get(String.self, at: "favorites")) ?? ""

        let requestedSports = Set(sportsParam.split(separator: ",").map(String.init))
        let favoriteTeams = Set(favoritesParam.split(separator: ",").map(String.init))

        // Load full schedule from Redis
        guard let schedule = try await req.kv.getJSON(
            RedisEndpoint.ESPN.latestSchedule.getValue(isDebug: req.application.environment == .development).rawValue,
            as: LiveScore.self
        ) else {
            throw NetworkError.invalidData
        }

        // Collect events from requested sports
        let sportEvents: [(String, LiveEvent?)] = [
            ("basketball", schedule.nba),
            ("soccer", schedule.soccer),
            ("hockey", schedule.nhl),
            ("mlb", schedule.mlb),
            ("nfl", schedule.nfl),
            ("golf", schedule.golf),
            ("tennis", schedule.tennis),
            ("racing", schedule.racing),
        ]

        var allGames: [Game] = []
        for (sportName, liveEvent) in sportEvents {
            guard requestedSports.isEmpty || requestedSports.contains(sportName) else { continue }
            if let events = liveEvent?.events {
                allGames.append(contentsOf: events)
            }
        }

        // Filter to upcoming games only
        let now = Calendar.current.startOfDay(for: Date())
        allGames = allGames.filter { ($0.isoDate ?? .distantPast) >= now }

        // Sort: favorites first, then by date
        allGames.sort { g1, g2 in
            let g1Fav = favoriteTeams.contains(g1.strHomeTeam) || favoriteTeams.contains(g1.strAwayTeam)
            let g2Fav = favoriteTeams.contains(g2.strHomeTeam) || favoriteTeams.contains(g2.strAwayTeam)
            if g1Fav && !g2Fav { return true }
            if !g1Fav && g2Fav { return false }
            return (g1.isoDate ?? .distantFuture) < (g2.isoDate ?? .distantFuture)
        }

        // Trim to limit
        let trimmed = Array(allGames.prefix(limit))

        // Strip heavy fields — keep only what the widget needs
        let strippedGames = trimmed.map { game -> Game in
            // Golf gets more leaderboard entries for the dedicated leaderboard widget
            let leaderboardLimit = (game.sportType == .golf) ? 8 : 3
            let strippedLeaderboard = game.leaderboardEntries?.prefix(leaderboardLimit).map { entry in
                LeaderboardEntry(
                    name: entry.name,
                    score: entry.score,
                    position: entry.position,
                    headshot: nil,
                    thruHole: entry.thruHole,
                    rounds: [],
                    constructor: entry.constructor,
                    gap: entry.gap,
                    movement: entry.movement
                )
            }

            // Trim lastPlay to top 3 lines (for legacy leaderboard parsing)
            let trimmedLastPlay: String? = game.lastPlay.flatMap { lp in
                let lines = lp.split(separator: "\n", omittingEmptySubsequences: false)
                return lines.isEmpty ? nil : lines.prefix(3).joined(separator: "\n")
            }

            return Game(
                idEvent: game.idEvent,
                idLeague: game.idLeague,
                idHomeTeam: game.idHomeTeam,
                idAwayTeam: game.idAwayTeam,
                strHomeTeam: game.strHomeTeam,
                strAwayTeam: game.strAwayTeam,
                intHomeScore: game.intHomeScore,
                intAwayScore: game.intAwayScore,
                strStatus: game.strStatus,
                strProgress: game.strProgress,
                strTimestamp: game.strTimestamp,
                lastPlay: trimmedLastPlay,
                homeLinescores: game.homeLinescores,
                awayLinescores: game.awayLinescores,
                isCompleted: game.isCompleted,
                isoDate: game.isoDate,
                leaderboardEntries: strippedLeaderboard.map(Array.init),
                sessions: game.sessions,
                venueName: game.venueName,
                homeRecord: game.homeRecord,
                awayRecord: game.awayRecord,
                circuitInfo: game.circuitInfo,
                legDisplay: game.legDisplay,
                aggregateScore: game.aggregateScore,
                homeSeed: game.homeSeed,
                awaySeed: game.awaySeed,
                playoff: game.playoff
            )
        }

        // Only include teams referenced by returned games
        let teamIDs = Set(strippedGames.flatMap { [$0.idHomeTeam, $0.idAwayTeam].compactMap { $0 } })
        let allTeams = try await req.kv.getJSON(
            RedisEndpoint.teams.getValue(isDebug: req.application.environment == .development).rawValue,
            as: [Team].self
        ) ?? []
        let relevantTeams = allTeams.filter { teamIDs.contains($0.idTeam ?? "") }

        let response = WidgetScheduleResponse(games: strippedGames, teams: relevantTeams)
        return encodeResult(res: response)
    }
}

/// Lightweight response for the widget schedule endpoint
struct WidgetScheduleResponse: Codable {
    let games: [Game]
    let teams: [Team]
}

func encodeResult(res: some Codable) -> String {
    let encoder = JSONEncoder()
    guard let resultString = try? encoder.encode(res) else { return "" }
    return String(data: resultString, encoding: .utf8) ?? ""
}

/// Fetches every ESPN league's scoreboard for one day (YYYYMMDD as Int) and
/// merges them into a single LiveScore grouped by sport. Mirrors the per-league
/// fetch used by `ESPNScheduleWindowJob`, but for an arbitrary date and with all
/// leagues folded into their sport's `LiveEvent`. Failures per league are
/// swallowed so one bad league doesn't sink the whole day.
func buildESPNScheduleForDate(dateInt: Int, client: some Client) async -> LiveScore {
    let targets = Leagues.allCases.filter { $0.espnSlug != nil }
    var bySport: [SportType: [Game]] = [:]
    let maxConcurrent = 6

    await withTaskGroup(of: (Leagues, Scoreboard?).self) { group in
        var iterator = targets.makeIterator()
        func addNext() {
            guard let league = iterator.next() else { return }
            group.addTask {
                let sb = try? await Integrator.getESPNScoreboard(for: league, client, dates: dateInt)
                return (league, sb)
            }
        }
        for _ in 0..<maxConcurrent { addNext() }
        while let (league, scoreboard) = await group.next() {
            if let scoreboard, let event = LiveEvent(events: scoreboard, league: league) {
                bySport[SportType(league: league), default: []].append(contentsOf: event.events)
            }
            addNext()
        }
    }

    func merged(_ sport: SportType) -> LiveEvent? {
        guard let games = bySport[sport], !games.isEmpty else { return nil }
        return LiveEvent(events: games)
    }

    return LiveScore(
        nba: merged(.basketball),
        mlb: merged(.mlb),
        soccer: merged(.soccer),
        nfl: merged(.nfl),
        nhl: merged(.hockey),
        golf: merged(.golf),
        tennis: merged(.tennis),
        racing: merged(.racing)
    )
}
